### ISSUE TITLE
User Inventory Float Value

### ISSUE THREAD

**Issue by Banana0008** [pepzwee/node-csgo-web-tradebot#180] opened 2020-10-25 15:17 UTC
Hi, I know that the repository is not maintained or support anymore but did anyone found a way to get the float value?

**Comment by iDefineHD** [comment] 2020-10-25 15:20
@Banana0008 the float value of what? the script wasw updated a few years back to include csgo float values.

**Comment by iDefineHD** [comment] 2020-10-25 15:21
Closing, as the issue is null. Already included within the script.

**Closed as completed by iDefineHD** 2020-10-25 15:21 UTC

**Comment by Banana0008** [comment] 2020-10-25 15:36
What I mean is to return me the actual value of the float ex: AWP I Dragon Lore (Fiel-Tested) 0.014554 --> This Value ; It only returns me the state of the skin not the actually float value

**Comment by pepzwee** [comment] 2020-10-25 15:39
https://github.com/pepzwee/node-csgo-web-tradebot/blob/master/lib/bots.js#L155-L184

Floats are for bots, not user inventories. Code might need updating if it's not working.
Good luck.

**Comment by Banana0008** [comment] 2020-10-25 18:44
@pepzwee Thanks I'll try it, and one more thing why this not works : "a v-for="item in userInventory" href="{{ item.inspect }}" ", I mean If is not on a href it gives me the right link. Thanks In Advance
